/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Forms;

import java.awt.Color;

/**
 *
 * @author iago
 */
public class MainForm extends javax.swing.JFrame {
       
    private final int[] cores;
    /**
     * Creates new form MainForm
     */
    public MainForm() {
        this.cores = new int[3];
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jSlider8 = new javax.swing.JSlider();
        jSpinner5 = new javax.swing.JSpinner();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel6 = new javax.swing.JPanel();
        plColorRGB = new javax.swing.JPanel();
        edtColorHexRGB = new javax.swing.JTextField();
        btnGerarColorRGB = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        slRedRGB = new javax.swing.JSlider();
        spRedRGB = new javax.swing.JSpinner();
        jPanel1 = new javax.swing.JPanel();
        slGreenRGB = new javax.swing.JSlider();
        spGreenRGB = new javax.swing.JSpinner();
        jPanel5 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        slBlueRGB = new javax.swing.JSlider();
        spBlueRGB = new javax.swing.JSpinner();
        jPanel7 = new javax.swing.JPanel();
        plColorCMYK = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        slCianoCMYK = new javax.swing.JSlider();
        spCianoCMYK = new javax.swing.JSpinner();
        jPanel10 = new javax.swing.JPanel();
        slMagentaCMYK = new javax.swing.JSlider();
        spMagentaCMYK = new javax.swing.JSpinner();
        jPanel11 = new javax.swing.JPanel();
        slYellowCMYK = new javax.swing.JSlider();
        spYellowCMYK = new javax.swing.JSpinner();
        btnGerarColorCMYK = new javax.swing.JButton();
        edtColorHexCMYK = new javax.swing.JTextField();
        jPanel13 = new javax.swing.JPanel();
        slBlackCMYK = new javax.swing.JSlider();
        spBlackCMYK = new javax.swing.JSpinner();

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Vermelho"));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jSlider8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSpinner5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 40, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSlider8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jSpinner5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        plColorRGB.setBackground(java.awt.Color.black);

        javax.swing.GroupLayout plColorRGBLayout = new javax.swing.GroupLayout(plColorRGB);
        plColorRGB.setLayout(plColorRGBLayout);
        plColorRGBLayout.setHorizontalGroup(
            plColorRGBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 145, Short.MAX_VALUE)
        );
        plColorRGBLayout.setVerticalGroup(
            plColorRGBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 118, Short.MAX_VALUE)
        );

        btnGerarColorRGB.setText("Gerar Cor");
        btnGerarColorRGB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGerarColorRGBMouseClicked(evt);
            }
        });

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Red"));

        slRedRGB.setMaximum(255);
        slRedRGB.setValue(0);
        slRedRGB.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                slRedRGBStateChanged(evt);
            }
        });

        spRedRGB.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spRedRGBStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(slRedRGB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(spRedRGB, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(spRedRGB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(slRedRGB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Green"));

        slGreenRGB.setMaximum(255);
        slGreenRGB.setToolTipText("");
        slGreenRGB.setValue(0);
        slGreenRGB.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                slGreenRGBStateChanged(evt);
            }
        });

        spGreenRGB.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spGreenRGBStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(slGreenRGB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spGreenRGB, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(spGreenRGB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(slGreenRGB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 301, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 64, Short.MAX_VALUE)
        );

        jPanel12.setBorder(javax.swing.BorderFactory.createTitledBorder("Blue"));

        slBlueRGB.setMaximum(255);
        slBlueRGB.setValue(0);
        slBlueRGB.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                slBlueRGBStateChanged(evt);
            }
        });

        spBlueRGB.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spBlueRGBStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(slBlueRGB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spBlueRGB, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(spBlueRGB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(slBlueRGB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(plColorRGB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnGerarColorRGB, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                        .addComponent(edtColorHexRGB)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(plColorRGB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(edtColorHexRGB, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnGerarColorRGB))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, 64, Short.MAX_VALUE))))
                .addContainerGap(86, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("RGB", jPanel6);

        plColorCMYK.setBackground(java.awt.Color.black);

        javax.swing.GroupLayout plColorCMYKLayout = new javax.swing.GroupLayout(plColorCMYK);
        plColorCMYK.setLayout(plColorCMYKLayout);
        plColorCMYKLayout.setHorizontalGroup(
            plColorCMYKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 145, Short.MAX_VALUE)
        );
        plColorCMYKLayout.setVerticalGroup(
            plColorCMYKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 118, Short.MAX_VALUE)
        );

        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder("Ciano"));

        slCianoCMYK.setMaximum(255);
        slCianoCMYK.setValue(0);
        slCianoCMYK.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                slCianoCMYKStateChanged(evt);
            }
        });

        spCianoCMYK.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spCianoCMYKStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(slCianoCMYK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(spCianoCMYK, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(spCianoCMYK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(slCianoCMYK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder("Magenta"));

        slMagentaCMYK.setMaximum(255);
        slMagentaCMYK.setToolTipText("");
        slMagentaCMYK.setValue(0);
        slMagentaCMYK.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                slMagentaCMYKStateChanged(evt);
            }
        });

        spMagentaCMYK.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spMagentaCMYKStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(slMagentaCMYK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spMagentaCMYK, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(spMagentaCMYK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(slMagentaCMYK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel11.setBorder(javax.swing.BorderFactory.createTitledBorder("Yellow"));

        slYellowCMYK.setMaximum(255);
        slYellowCMYK.setValue(0);
        slYellowCMYK.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                slYellowCMYKStateChanged(evt);
            }
        });

        spYellowCMYK.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spYellowCMYKStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(slYellowCMYK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spYellowCMYK, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(spYellowCMYK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(slYellowCMYK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnGerarColorCMYK.setText("Gerar Cor");
        btnGerarColorCMYK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGerarColorCMYKMouseClicked(evt);
            }
        });

        jPanel13.setBorder(javax.swing.BorderFactory.createTitledBorder("Black"));

        slBlackCMYK.setMaximum(255);
        slBlackCMYK.setValue(0);
        slBlackCMYK.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                slBlackCMYKStateChanged(evt);
            }
        });

        spBlackCMYK.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spBlackCMYKStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(slBlackCMYK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spBlackCMYK, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(spBlackCMYK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(slBlackCMYK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(plColorCMYK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnGerarColorCMYK, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                        .addComponent(edtColorHexCMYK)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(plColorCMYK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(edtColorHexCMYK, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnGerarColorCMYK))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("CMYK", jPanel7);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 483, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Gerar cor a partir do sistema de cores cmyk
     * 
     * @param c
     * @param m
     * @param y
     * @param k
     * @return 
     */ 
    public Color calculaCMYK(int c, int m, int y, int k){
        c = Math.min(255, c + k);
        m = Math.min(255, m + k);
        y = Math.min(255, y + k);        
        
        cores[0] = 255 - c;
        cores[1] = 255 - m;
        cores[2] = 255 - y;
        
        return new Color(cores[0], cores[1], cores[2]);
    }
    
    /**
     * Outra forma de gerar cor a partir
     * do sistema de cor cmyk
     * 
     * @param c
     * @param m
     * @param y
     * @param k
     * @return 
     */
    public Color calculaCMYKmodelo2(int c, int m, int y, int k){
        
        int cor = 255 - k;
        cores[0] = cor * (255 - c)/255;
        cores[1] = cor * (255 - m)/255;
        cores[2] = cor * (255 - y)/255;
        
        return new Color(cores[0], cores[1], cores[2]);
    }
    
    /**
     * Calcula o valor em hexadecimal de uma
     * determinada cor especificada em rgb
     * 
     * @param r
     * @param g
     * @param b
     * @return 
     */
    public String calculaHexa(int r, int g, int b){
        String resp = "";
        
        resp += checkValue((int) r/16);
        resp += checkValue((int) r%16);
        resp += checkValue((int) g/16);
        resp += checkValue((int) g%16);
        resp += checkValue((int) b/16);
        resp += checkValue((int) b%16);
        
        return resp;
    }
    
    /**
     * Método que auxilia na conversão para hexadecimal
     * verifica se o valor esta entre 10 e 15 e retorna valor
     * em hexadecimal
     * 
     * @param value
     * @return 
     */
    public String checkValue(int value){
        String resp = "";
        
        switch(value){
            case 10:    resp = "A";
                break;
            case 11:    resp = "B";
                break;
            case 12:    resp = "C";
                break;
            case 13:    resp = "D";
                break;
            case 14:    resp = "E";
                break;
            case 15:    resp = "F";
                break;            
            default:    resp += value;
                break;
        }
        return resp;
    }
    
    /**
     * Alterar a cor de fundo do panel RGB
     * ao alterar valor do slider
     */
    public void setBackgroundColorPanelRGBsl(){        
        plColorRGB.setBackground(
                new Color(slRedRGB.getValue(),
                        slGreenRGB.getValue(),
                        slBlueRGB.getValue()));
    }
    
    /**
     * Alterar a cor de fundo do panel RGB
     * ao alterar valor do spinner
     */
    public void setBackgroundColorPanelRGBsp(){        
        plColorRGB.setBackground(
                new Color(Integer.parseInt(spRedRGB.getValue().toString()),
                Integer.parseInt(spGreenRGB.getValue().toString()),
                Integer.parseInt(spBlueRGB.getValue().toString())));
    }
    
    /**
     * Alterar a cor de fundo do panel CMYK
     * ao alterar valor do slider
     */
    public void setBackgroundColorPanelCMYKsl(){        
        plColorCMYK.setBackground(calculaCMYKmodelo2(slCianoCMYK.getValue(),
                slMagentaCMYK.getValue(), 
                slYellowCMYK.getValue(),
                slBlackCMYK.getValue()));
    }
   
    /**
     * Alterar a cor de fundo do panel CMYK
     * ao alterar valor do spinner
     */
    public void setBackgroundColorPanelCMYKsp(){        
        plColorCMYK.setBackground(
                 calculaCMYKmodelo2(
                        Integer.parseInt(spCianoCMYK.getValue().toString()),
                        Integer.parseInt(spMagentaCMYK.getValue().toString()),
                        Integer.parseInt(spYellowCMYK.getValue().toString()),
                        Integer.parseInt(spBlackCMYK.getValue().toString())                
                 ));
    }
    
    
    private void slRedRGBStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_slRedRGBStateChanged
        // TODO add your handling code here:        
        spRedRGB.setValue(slRedRGB.getValue());        
        setBackgroundColorPanelRGBsl();        
    }//GEN-LAST:event_slRedRGBStateChanged

    private void slGreenRGBStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_slGreenRGBStateChanged
        // TODO add your handling code here:
        spGreenRGB.setValue(slGreenRGB.getValue());
        setBackgroundColorPanelRGBsl();
    }//GEN-LAST:event_slGreenRGBStateChanged

    private void slBlueRGBStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_slBlueRGBStateChanged
        // TODO add your handling code here:
        spBlueRGB.setValue(slBlueRGB.getValue());
        setBackgroundColorPanelRGBsl();
    }//GEN-LAST:event_slBlueRGBStateChanged

    private void spRedRGBStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spRedRGBStateChanged
        // TODO add your handling code here:
        slRedRGB.setValue(Integer.parseInt(spRedRGB.getValue().toString()));
        setBackgroundColorPanelRGBsp();
    }//GEN-LAST:event_spRedRGBStateChanged

    private void spGreenRGBStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spGreenRGBStateChanged
        // TODO add your handling code here:
        slGreenRGB.setValue(Integer.parseInt(spGreenRGB.getValue().toString()));
        setBackgroundColorPanelRGBsp();
    }//GEN-LAST:event_spGreenRGBStateChanged

    private void spBlueRGBStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spBlueRGBStateChanged
        // TODO add your handling code here:
        slBlueRGB.setValue(Integer.parseInt(spBlueRGB.getValue().toString()));
        setBackgroundColorPanelRGBsp();
    }//GEN-LAST:event_spBlueRGBStateChanged

    private void btnGerarColorRGBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGerarColorRGBMouseClicked
        // TODO add your handling code here:
        edtColorHexRGB.setText("#"+calculaHexa(slRedRGB.getValue(),
                slGreenRGB.getValue(),
                slBlueRGB.getValue()));       
    }//GEN-LAST:event_btnGerarColorRGBMouseClicked

    private void slCianoCMYKStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_slCianoCMYKStateChanged
        // TODO add your handling code here:
        spCianoCMYK.setValue(slCianoCMYK.getValue());
        setBackgroundColorPanelCMYKsl();        
    }//GEN-LAST:event_slCianoCMYKStateChanged

    private void spCianoCMYKStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spCianoCMYKStateChanged
        // TODO add your handling code here:
        slCianoCMYK.setValue(Integer.parseInt(spCianoCMYK.getValue().toString()));
        setBackgroundColorPanelCMYKsp();
    }//GEN-LAST:event_spCianoCMYKStateChanged

    private void slMagentaCMYKStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_slMagentaCMYKStateChanged
        // TODO add your handling code here:        
        spMagentaCMYK.setValue(slMagentaCMYK.getValue());
        setBackgroundColorPanelCMYKsl();
    }//GEN-LAST:event_slMagentaCMYKStateChanged

    private void spMagentaCMYKStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spMagentaCMYKStateChanged
        // TODO add your handling code here:
        slMagentaCMYK.setValue(
                Integer.parseInt(spMagentaCMYK.getValue().toString()));
        setBackgroundColorPanelCMYKsp();
    }//GEN-LAST:event_spMagentaCMYKStateChanged

    private void slYellowCMYKStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_slYellowCMYKStateChanged
        // TODO add your handling code here:
        spYellowCMYK.setValue(slYellowCMYK.getValue());
        setBackgroundColorPanelCMYKsl();
    }//GEN-LAST:event_slYellowCMYKStateChanged

    private void spYellowCMYKStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spYellowCMYKStateChanged
        // TODO add your handling code here:
        slYellowCMYK.setValue(
                Integer.parseInt(spYellowCMYK.getValue().toString()));
        setBackgroundColorPanelCMYKsp();
    }//GEN-LAST:event_spYellowCMYKStateChanged

    private void btnGerarColorCMYKMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGerarColorCMYKMouseClicked
        // TODO add your handling code here:
        edtColorHexCMYK.setText("#"+calculaHexa(cores[0], cores[1], cores[2]));        
    }//GEN-LAST:event_btnGerarColorCMYKMouseClicked

    private void slBlackCMYKStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_slBlackCMYKStateChanged
        // TODO add your handling code here:
        spBlackCMYK.setValue(slBlackCMYK.getValue());
        setBackgroundColorPanelCMYKsl();
    }//GEN-LAST:event_slBlackCMYKStateChanged

    private void spBlackCMYKStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spBlackCMYKStateChanged
        // TODO add your handling code here:
        slBlackCMYK.setValue(
                Integer.parseInt(spBlackCMYK.getValue().toString()));
        setBackgroundColorPanelCMYKsp();
    }//GEN-LAST:event_spBlackCMYKStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Classic".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGerarColorCMYK;
    private javax.swing.JButton btnGerarColorRGB;
    private javax.swing.JTextField edtColorHexCMYK;
    private javax.swing.JTextField edtColorHexRGB;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JSlider jSlider8;
    private javax.swing.JSpinner jSpinner5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel plColorCMYK;
    private javax.swing.JPanel plColorRGB;
    private javax.swing.JSlider slBlackCMYK;
    private javax.swing.JSlider slBlueRGB;
    private javax.swing.JSlider slCianoCMYK;
    private javax.swing.JSlider slGreenRGB;
    private javax.swing.JSlider slMagentaCMYK;
    private javax.swing.JSlider slRedRGB;
    private javax.swing.JSlider slYellowCMYK;
    private javax.swing.JSpinner spBlackCMYK;
    private javax.swing.JSpinner spBlueRGB;
    private javax.swing.JSpinner spCianoCMYK;
    private javax.swing.JSpinner spGreenRGB;
    private javax.swing.JSpinner spMagentaCMYK;
    private javax.swing.JSpinner spRedRGB;
    private javax.swing.JSpinner spYellowCMYK;
    // End of variables declaration//GEN-END:variables
}
